#epi
- type: playTimeTracker
  id: JobJusticar

 # cco
- type: playTimeTracker
  id: JobCentralCommandDirector

# command
- type: playTimeTracker
  id: JobConsularOfficer

- type: playTimeTracker
  id: JobDiplomatBodyguard

- type: playTimeTracker
  id: JobDiplomatSecretary
