- type: job
  id: ConsularOfficer
  name: Consular Officer
  description: "Represent your government, act as a diplomat, ensure your citizens are treated fairly, work with the magistrate to uphold sectoral law, cry to the president when they arrest you"
  playTimeTracker: JobConsularOfficer
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Command
    min: 54000 # 15 hours
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    #- Foreigner // this might be kinda fun i dunno
    #- ForeignerLight
    - Muted
  - !type:CharacterEmployerRequirement # add government body employers? atleast for major factions anyways
    employers:
    - BieselRepGov
    - SolGov
    - PRCAGov
    - ElyraGov
    - MidasGroup
  weight: 20
  startingGear: ConsularOfficerGear
  icon: "JobIconConsulate"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - CentralCommand
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - ConsularOfficer
  - Lawyer
  - Cargo
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: ConsularOfficerGear
  subGear:
  - ConsulatePlasmamanGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ConsularOfficerPDA
    jumpsuit: ClothingUniformJumpsuitConsularBlackSuit
    back: ClothingBackpackSatchel
    ears: ClothingHeadsetAltCentCom

- type: startingGear
  id: ConsulatePlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitNanotrasenRepresentative
    head: ClothingHeadEnvirohelmNanotrasenRepresentative
    gloves: ClothingHandsGlovesEnviroglovesBlack

- type: startingGear
  id: BieselFactionGear
  requirements:
  - !type:CharacterEmployerRequirement # I DONT KNOW MAAAAN make this work later
    employers:
    - BieselRepGov
  subGear:
  - ConsulatePlasmamanGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ConsularOfficerPDA
    jumpsuit: ClothingUniformJumpsuitBieselConsular
    back: ClothingBackpackSatchel
    ears: ClothingHeadsetAltCentCom
    pocket1: BieselRepLockerTeleporter
    pocket2: BieselLanyard

- type: startingGear
  id: PRAFactionGear
  requirements:
  - !type:CharacterEmployerRequirement
    employers:
    - PRCAGov
  equipment:
    shoes: ClothingShoesColorBlack
    id: ConsularOfficerPDA
    jumpsuit: ClothingUniformJumpsuitPRAConsular
    back: ClothingBackpackSatchel
    ears: ClothingHeadsetAltCentCom
    pocket1: PRARepLockerTeleporter
    pocket2: PRALanyard

- type: startingGear
  id: SolFactionGear
  requirements:
  - !type:CharacterEmployerRequirement
    employers:
    - SolGov
  equipment:
    shoes: ClothingShoesColorBlack
    id: ConsularOfficerPDA
    jumpsuit: ClothingUniformJumpsuitConsularBlackSuit
    back: ClothingBackpackSatchel
    ears: ClothingHeadsetAltCentCom
    pocket1: SolRepLockerTeleporter
    pocket2: SANIdCard

- type: startingGear
  id: GoldenDeepFactionGear
  requirements:
  - !type:CharacterEmployerRequirement
    employers:
    - MidasGroup
  equipment:
    shoes: ClothingShoesColorBlack
    id: ConsularOfficerPDA
    jumpsuit: ClothingUniformJumpsuitGDGrandConsular
    back: ClothingBackpackSatchel
    ears: ClothingHeadsetAltCentCom
    pocket1: GoldenDeepRepLockerTeleporter
    pocket2: GoldenDeepRingID

- type: startingGear
  id: ElyraFactionGear
  requirements:
  - !type:CharacterEmployerRequirement
    employers:
    - ElyraGov
  equipment:
    shoes: ClothingShoesColorBlack
    id: ConsularOfficerPDA
    jumpsuit: ClothingUniformJumpsuitConsularBlackSuit
    back: ClothingBackpackSatchel
    ears: ClothingHeadsetAltCentCom
    pocket1: ElyraRepLockerTeleporter
    pocket2: ElyraLanyard
