- type: ghostRole
  id: BodyguardBiesel
  name: ghost-role-information-biesel-bodyguard-reinforcement-name
  description: ghost-role-information-biesel-bodyguard-reinforcement-description
  rules: ghost-role-information-consulate-bodyguard-rules
  entityPrototype: RandomHumanoidSpawnerBieselBodyguard

- type: ghostRole
  id: BodyguardPRA
  name: ghost-role-information-pra-bodyguard-reinforcement-name
  description: ghost-role-information-pra-bodyguard-reinforcement-description
  rules: ghost-role-information-consulate-bodyguard-rules
  entityPrototype: PRABodyguard

- type: ghostRole
  id: BodyguardHoplan
  name: ghost-role-information-goldendeep-bodyguard-reinforcement-name
  description: ghost-role-information-goldendeep-bodyguard-reinforcement-description
  rules: ghost-role-information-consulate-bodyguard-rules
  entityPrototype: HoplanBodyguard

- type: ghostRole
  id: BodyguardSAN
  name: ghost-role-information-sol-bodyguard-reinforcement-name
  description: ghost-role-information-sol-bodyguard-reinforcement-description
  rules: ghost-role-information-consulate-bodyguard-rules
  entityPrototype: SANBodyguard

- type: ghostRole
  id: BodyguardElyra
  name: ghost-role-information-elyra-bodyguard-reinforcement-name
  description: ghost-role-information-elyra-bodyguard-reinforcement-description
  rules: ghost-role-information-consulate-bodyguard-rules
  entityPrototype: ElyraBodyguard

# SECRETARY -- consildate this to a secretary with single use chameleon clothes or something maybe

- type: ghostRole
  id: AssistantBiesel
  name: ghost-role-information-biesel-assistant-reinforcement-name
  description: ghost-role-information-biesel-assistant-reinforcement-description
  rules: ghost-role-information-consulate-assistant-rules
  entityPrototype: RandomHumanoidSpawnerBieselSecretary

- type: ghostRole
  id: AssistantSAN
  name: ghost-role-information-sol-assistant-reinforcement-name
  description: ghost-role-information-sol-assistant-reinforcement-description
  rules: ghost-role-information-consulate-assistant-rules
  entityPrototype: SANSecretary

- type: ghostRole
  id: AssistantPRA
  name: ghost-role-information-pra-assistant-reinforcement-name
  description: ghost-role-information-pra-assistant-reinforcement-description
  rules: ghost-role-information-consulate-assistant-rules
  entityPrototype: PRASecretary

- type: ghostRole
  id: AssistantElyra
  name: ghost-role-information-elyra-assistant-reinforcement-name
  description: ghost-role-information-elyra-assistant-reinforcement-description
  rules: ghost-role-information-consulate-assistant-rules
  entityPrototype: ElyraSecretary

- type: ghostRole
  id: AssistantGoldenDeep
  name: ghost-role-information-goldendeep-assistant-reinforcement-name
  description: ghost-role-information-goldendeep-assistant-reinforcement-description
  rules: ghost-role-information-consulate-assistant-rules
  entityPrototype: GoldenDeepSecretary
